# Generated by Django 4.1.13 on 2024-09-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetable',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
